name: Sanity check

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  run-sanity-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run detekt
        run: ./gradlew detekt

      - name: Cleanup
        if: always()
        run: ./gradlew clean
