name: Unit tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  execute-unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests
        run: ./gradlew unitTests

      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-report
          path: build/reports/tests/aggregate

      - name: Cleanup
        if: always()
        run: ./gradlew clean
